apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: k8s-ns
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
        - key: gpu
          operator: "Equal"
          value: yeah
          effect: NoSchedule
      containers:
      - name: nginx
        image: nginx:1.25.4
        ports:
        - containerPort: 80
          name: http
     
