apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: learning
spec:
  containers:
  - image: ubuntu:22.04
    name: dnsutils
    command:
    - sleep
    - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always