---
apiVersion: v1
kind: Secret
metadata:
  name: sql-passwd
  namespace: k8s-ns
data:
  passwd: UEBzc3cwcmQxMjM= 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-config
  namespace: k8s-ns
data:
  cnf: |
    [mysqld]
    slow-query-log = 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql
  namespace: k8s-ns
  labels:
    app: sql
spec:
  serviceName: sql
  replicas: 3
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: topology.kubernetes.io/zone
            labelSelector:
              matchLabels:
                app: web
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: topology.kubernetes.io/zone
            labelSelector:
              matchLabels:
                app: sql
      containers:
      - name: database
        image: mysql:latest
        ports:
        - containerPort: 3306
          name: sql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-passwd
              key: passwd
        - name: MYSQL_CONFIGURATION
          valueFrom:
            configMapKeyRef:
              name: sql-config
              key: cnf

---
apiVersion: v1
kind: Service
metadata:
  name: sql
  namespace: k8s-ns
spec:
  type: LoadBalancer
  ports:
  - name: sql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: sql
