apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-sa
  name: pod-sa
  namespace: k8s-ns
spec:
  serviceAccountName: pod-sa
  containers:
  - command:
    - sleep
    - "10000"
    image: nginx
    name: pod-sa

