apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-label-annotate
  namespace: k8s-ns
  annotations:
    config: prod
  labels:
    app: nginx
    owner: myOwner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      owner: myOwner
  template:
    metadata:
      labels:
        app: nginx
        owner: myOwner
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        ports:
        - containerPort: 80

