apiVersion: v1
kind: Secret
metadata:
  name: mysql-passwd
  namespace: k8s-ns
data:
  passwd: UEBzc3cwcmQxMjM= 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: k8s-ns
data:
  cnf: |
    [mysqld]
    slow-query-log = 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: k8s-ns
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 5
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: topology.kubernetes.io/zone
            labelSelector:
              matchLabels:
                app: nginx
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: topology.kubernetes.io/zone
            labelSelector:
              matchLabels:
                app: mysql
      containers:
      - name: database
        image: mysql:latest
        ports:
        - containerPort: 3306
          name: sql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-passwd
              key: passwd
        - name: MYSQL_CONFIGURATION
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: cnf

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: k8s-ns
spec:
  type: NodePort
  ports:
  - name: sql
    port: 3306
    protocol: TCP
    targetPort: sql
  selector:
    app: mysql
