apiVersion: audit.k8s.io/v1 
kind: Policy
omitStages:
  - "RequestReceived"
rules:
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["pods"]
    namespaces: ["k8s-ns", "security-k8s-ns"]
    
  - level: Metadata
    resources:
    - group: ""
      resources: ["pods/log", "pods/status"]
    namespaces: ["k8s-ns", "security-k8s-ns"]

  - level: Request
    resources:
    - group: "" 
      resources: ["configmaps"]
    namespaces: ["k8s-ns", "security-k8s-ns"]

  - level: Metadata
    omitStages:
      - "RequestReceived"
    namespaces: ["k8s-ns", "security-k8s-ns"]

  - level: None
