apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-pvc
  namespace: k8s-ns
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginx-data
      volumes:
      - name: nginx-data
        configMap:
          name: nginx-conf
          items:
          - key: website
            path: website

