---
apiVersion: v1
kind: Pod
metadata:
  name: sec-context
  namespace: k8s-ns
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: sec-ctx
    emptyDir: {}
  containers:
  - name: security-demo
    image: busybox:1.36.1
    command: 
      - sh
      - -c 
      - sleep 1h
    volumeMounts:
    - mountPath: /data/demo
      name: sec-ctx
    securityContext: 
      allowPrivilegeEscalation: false



