apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 4 
  template:
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            cpu: "1" 
            memory: "1Gi" 
          requests:
            cpu: "500m" 
            memory: "512Mi" 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
